services:
  node-registry:
    image: ${SECURECHAT_IMAGE_PREFIX:?Missing SECURECHAT_IMAGE_PREFIX}-node-registry:${SECURECHAT_IMAGE_TAG:?Missing SECURECHAT_IMAGE_TAG}
    build: !reset null
    pull_policy: always

  presence-directory:
    image: ${SECURECHAT_IMAGE_PREFIX:?Missing SECURECHAT_IMAGE_PREFIX}-presence-directory:${SECURECHAT_IMAGE_TAG:?Missing SECURECHAT_IMAGE_TAG}
    build: !reset null
    pull_policy: always

  push:
    image: ${SECURECHAT_IMAGE_PREFIX:?Missing SECURECHAT_IMAGE_PREFIX}-push:${SECURECHAT_IMAGE_TAG:?Missing SECURECHAT_IMAGE_TAG}
    build: !reset null
    pull_policy: always
